/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32;

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport;

@Deprecated
public class BFI_A8_338 extends ParseSupport {

	public static final BFI_A8_338 INSTANCE = new BFI_A8_338();

	@Override
	protected String getOpCode(int data) {
		return "BFI.W";
	}
	@Override
	public void performExecuteCommand(int data) {
	}

}