/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32;

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport;
import static brilliant.arm.OpCode.OpUtil.*;
import static brilliant.vm.OS.*;
import static brilliant.vm.Register.*;

public class BXJ_A8_354 extends ParseSupport {

	public static final BXJ_A8_354 INSTANCE = new BXJ_A8_354();

	@Override
	protected String getOpCode(int data) {
		return "BXJ";
	}

	@Override
	protected int getRm(int data) {
		return getShiftInt(data, 16, 4);
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}