/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32;

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport;
import static brilliant.arm.OpCode.OpUtil.*;
import static brilliant.vm.OS.*;
import static brilliant.vm.Register.*;

public class LDRSH_A8_460 extends ParseSupport {

	public static final LDRSH_A8_460 INSTANCE = new LDRSH_A8_460();

	@Override
	public String parse(int data) {

		StringBuilder sb = new StringBuilder("LDRSH.W ");
		int Rt = getShiftInt(data, 12, 4);
		int imm12 = getShiftInt(data, 0, 12);
		boolean add = getShiftInt(data, 23, 1) == 0b1;
		sb.append(parseRegister(Rt));
		sb.append(" , [PC , #");
		if (!add)
			sb.append("-");
		sb.append(imm12);
		sb.append("]");

		return sb.toString();

	}

	@Override
	public void performExecuteCommand(int data) {
	}

}