/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32;

import static brilliant.arm.OpCode.factory.OpUtil.getShiftInt;
import static brilliant.arm.OpCode.factory.OpUtil.parseRegister;
import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport;

public class LDRSB_A8_452 extends ParseSupport {

	public static final LDRSB_A8_452 INSTANCE = new LDRSB_A8_452();

	@Override
	public String parse(int data) {

		StringBuilder sb = new StringBuilder("LDRSB.W ");
		int Rt = getShiftInt(data, 12, 4);
		int imm12 = getShiftInt(data, 0, 12);
		boolean add = getShiftInt(data, 23, 1) == 0b1;
		sb.append(parseRegister(Rt));
		sb.append(" , [PC , #");
		if (!add)
			sb.append("-");
		sb.append(imm12);
		sb.append("]");

		return sb.toString();

	}

	@Override
	public void performExecuteCommand(int data) {
	}

}