/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32;

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport;
import static brilliant.elf.vm.OS.*;
import static brilliant.elf.vm.Register.*;
import static brilliant.arm.OpCode.OpUtil.*;

public class MLA_A8_480 extends ParseSupport {

	public static final MLA_A8_480 INSTANCE = new MLA_A8_480();

	@Override
	protected String getOpCode(int data) {
		return "MLA";
	}

	@Override
	protected int getRd(int data) {
		return getShiftInt(data, 8, 4);
	}

	@Override
	protected int getRn(int data) {
		return getShiftInt(data, 16, 4);
	}

	@Override
	protected int getRm(int data) {
		return getShiftInt(data, 0, 4);
	}

	@Override
	protected int getShift(int data) {
		return getShiftInt(data, 12, 4);
	}

	@Override
	protected boolean shifterRegister() {
		return true;
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}