/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32;

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport;

@Deprecated
public class MOVT_A8_491 extends ParseSupport {

	public static final MOVT_A8_491 INSTANCE = new MOVT_A8_491();

	@Override
	protected String getOpCode(int data) {
		return "MOVT.W";
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}