/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32;

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport;

@Deprecated
public class MRS_B9_1990 extends ParseSupport {

	public static final MRS_B9_1990 INSTANCE = new MRS_B9_1990();

	@Override
	protected String getOpCode(int data) {
		return "MRS.W";
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}