/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32;

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport;

@Deprecated
public class MSR_B9_1998 extends ParseSupport {

	public static final MSR_B9_1998 INSTANCE = new MSR_B9_1998();

	@Override
	protected String getOpCode(int data) {
		return "MSR.W";
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}