/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32;

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport;

@Deprecated
public class PKH_A8_522 extends ParseSupport {

	public static final PKH_A8_522 INSTANCE = new PKH_A8_522();

	@Override
	protected String getOpCode(int data) {
		return "PKH";
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}