/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32;

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport;

@Deprecated
public class PLD_A8_528 extends ParseSupport {

	public static final PLD_A8_528 INSTANCE = new PLD_A8_528();

	@Override
	protected String getOpCode(int data) {
		return "PLD";
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}