/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32;

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport;

@Deprecated
public class PLI_A8_532 extends ParseSupport {

	public static final PLI_A8_532 INSTANCE = new PLI_A8_532();

	@Override
	protected String getOpCode(int data) {
		return "PLI";
	}
	@Override
	public void performExecuteCommand(int data) {
	}

}