/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32;

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport;
import static brilliant.elf.vm.OS.*;
import static brilliant.elf.vm.Register.*;
import static brilliant.arm.OpCode.OpUtil.*;

public class QDADD_A8_548 extends ParseSupport {

	public static final QDADD_A8_548 INSTANCE = new QDADD_A8_548();

	@Override
	protected String getOpCode(int data) {
		return "QDADD";
	}

	@Override
	protected int getRd(int data) {
		return getShiftInt(data, 8, 4);
	}

	@Override
	protected int getRn(int data) {
		return getShiftInt(data, 0, 4); // <opcode> <Rd> , <Rm> , <Rn> ,exchage
										// Rn and Rm
	}

	@Override
	protected int getRm(int data) {
		return getShiftInt(data, 16, 4);
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}