/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32;

import static brilliant.arm.OpCode.factory.OpUtil.getShiftInt;
import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport;

public class RBIT_A8_560 extends ParseSupport {

	public static final RBIT_A8_560 INSTANCE = new RBIT_A8_560();

	@Override
	protected String getOpCode(int data) {
		return "RBIT";
	}

	@Override
	protected int getRd(int data) {
		return getShiftInt(data, 8, 4);
	}

	@Override
	protected int getRm(int data) {

		if (getShiftInt(data, 16, 4) != getShiftInt(data, 0, 4))
			error(data);

		return getShiftInt(data, 16, 4);
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}