/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32;

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport;

@Deprecated
public class RFE_B9_2000 extends ParseSupport {

	public static final RFE_B9_2000 INSTANCE = new RFE_B9_2000();

	@Override
	protected String getOpCode(int data) {
		return "RFE.W";
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}