/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32;

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport;

@Deprecated
public class SMC_B9_2002 extends ParseSupport {

	public static final SMC_B9_2002 INSTANCE = new SMC_B9_2002();

	@Override
	protected String getOpCode(int data) {
		return "SMC.W";
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}