/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32;

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport;

@Deprecated
public class SMLAD_A8_622 extends ParseSupport {

	public static final SMLAD_A8_622 INSTANCE = new SMLAD_A8_622();

	@Override
	protected String getOpCode(int data) {
		return "SMLAD";
	}
	@Override
	public void performExecuteCommand(int data) {
	}

}