/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32;

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport;

@Deprecated
public class SMLABB_A8_620 extends ParseSupport {

	public static final SMLABB_A8_620 INSTANCE = new SMLABB_A8_620();

	@Override
	protected String getOpCode(int data) {
		return "SMLABB";
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}