/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32;

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport;

@Deprecated
public class SMLSD_A8_632 extends ParseSupport {

	public static final SMLSD_A8_632 INSTANCE = new SMLSD_A8_632();

	@Override
	protected String getOpCode(int data) {
		return "SMLSD";
	}
	@Override
	public void performExecuteCommand(int data) {
	}

}