/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32;

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport;

@Deprecated
public class SMMLS_A8_638 extends ParseSupport {

	public static final SMMLS_A8_638 INSTANCE = new SMMLS_A8_638();

	@Override
	protected String getOpCode(int data) {
		return "SMMLS";
	}
	@Override
	public void performExecuteCommand(int data) {
	}

}