/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32;

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport;

@Deprecated
public class SMMLA_A8_636 extends ParseSupport {

	public static final SMMLA_A8_636 INSTANCE = new SMMLA_A8_636();

	@Override
	protected String getOpCode(int data) {
		return "SMMLA";
	}
	@Override
	public void performExecuteCommand(int data) {
	}

}