/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32;

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport;

@Deprecated
public class SMMUL_A8_640 extends ParseSupport {

	public static final SMMUL_A8_640 INSTANCE = new SMMUL_A8_640();

	@Override
	protected String getOpCode(int data) {
		return "SMMUL";
	}
	@Override
	public void performExecuteCommand(int data) {
	}

}