/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32;

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport;

@Deprecated
public class SMUAD_A8_642 extends ParseSupport {

	public static final SMUAD_A8_642 INSTANCE = new SMUAD_A8_642();

	@Override
	protected String getOpCode(int data) {
		return "SMUAD";
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}