/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32;

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport;

@Deprecated
public class SMULBB_A8_644 extends ParseSupport {

	public static final SMULBB_A8_644 INSTANCE = new SMULBB_A8_644();

	@Override
	protected String getOpCode(int data) {
		return "SMULBB";
	}
	@Override
	public void performExecuteCommand(int data) {
	}

}