/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32;

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport;

@Deprecated
public class SMULWB_A8_648 extends ParseSupport {

	public static final SMULWB_A8_648 INSTANCE = new SMULWB_A8_648();

	@Override
	protected String getOpCode(int data) {
		return "SMULWB";
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}