/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32;

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport;

@Deprecated
public class SMUSD_A8_650 extends ParseSupport {

	public static final SMUSD_A8_650 INSTANCE = new SMUSD_A8_650();

	@Override
	protected String getOpCode(int data) {
		return "SMUSD";
	}
	@Override
	public void performExecuteCommand(int data) {
	}

}