/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32;

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport;

@Deprecated
public class UDF_A8_758 extends ParseSupport {

	public static final UDF_A8_758 INSTANCE = new UDF_A8_758();

	@Override
	protected String getOpCode(int data) {
		return "UDF.W";
	}
	@Override
	public void performExecuteCommand(int data) {
	}

}