/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32;

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport;

@Deprecated
public class USADA8_A8_794 extends ParseSupport {

	public static final USADA8_A8_794 INSTANCE = new USADA8_A8_794();

	@Override
	protected String getOpCode(int data) {
		return "USADA8";
	}
	@Override
	public void performExecuteCommand(int data) {
	}

}