/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction32;

import brilliant.arm.OpCode.thumb.instruction32.support.ParseSupport;

@Deprecated
public class USAD8_A8_792 extends ParseSupport {

	public static final USAD8_A8_792 INSTANCE = new USAD8_A8_792();

	@Override
	protected String getOpCode(int data) {
		return "USAD8";
	}
	@Override
	public void performExecuteCommand(int data) {
	}

}