/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction;

import static brilliant.arm.OpCode.factory.OpUtil.getShiftInt;
import static brilliant.arm.OpCode.factory.OpUtil.signExtend;
import brilliant.arm.OpCode.arm.instruction.support.ParseSupport;

public class B_A8_334 extends ParseSupport {

	public static final B_A8_334 INSTANCE = new B_A8_334();

	@Override
	protected String getOpCode(int data) {
		return "B";
	}

	@Override
	protected int getShift(int data) {
		return signExtend(getShiftInt(data, 0, 24) << 2, 24);
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}