/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction;

import brilliant.arm.OpCode.arm.instruction.support.ParseSupport;

@Deprecated
public class HVC_B9_1984 extends ParseSupport {

	public static final HVC_B9_1984 INSTANCE = new HVC_B9_1984();

	@Override
	protected String getOpCode(int data) {
		return "HVC";
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}