/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction;

import static brilliant.arm.OpCode.factory.OpUtil.getShiftInt;

import brilliant.arm.OpCode.arm.instruction.support.ParseSupport;
import brilliant.arm.OpCode.factory.Remotable;
import brilliant.elf.vm.Register;

public class LDRB_A8_420 extends ParseSupport implements Remotable {

	public static final LDRB_A8_420 INSTANCE = new LDRB_A8_420();

	@Override
	public String parse(int data) {
		return LDRB_A8_418.INSTANCE.parse(data);
	}

	@Override
	protected String getCommnet(int data) {

		if (Register.PC <= 0)
			return null;

		return "@" + (offset(data) + Register.PC);
	}

	@Override
	protected boolean shifterUsed() {
		return true;
	}

	@Override
	public void performExecuteCommand(int data) {
	}

	@Override
	public int offset(int data) {
		int imm12 = getShiftInt(data, 0, 12);
		int add = getShiftInt(data, 23, 1);
		return add == 1 ? imm12 : -imm12;
	}

}