/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction;

import brilliant.arm.OpCode.arm.instruction.support.ParseSupport;
import static brilliant.arm.OpCode.factory.OpUtil.*;

public class LDREX_A8_432 extends ParseSupport {

	public static final LDREX_A8_432 INSTANCE = new LDREX_A8_432();

	@Override
	protected int getRd(int data) {
		return getShiftInt(data, 12, 4);
	}

	@Override
	protected int getRn(int data) {
		return getShiftInt(data, 16, 4);
	}

	@Override
	protected boolean isRnMemory() {
		return true;
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}