/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction;

import brilliant.arm.OpCode.arm.instruction.support.ParseSupport;
import static brilliant.arm.OpCode.factory.OpUtil.*;

public class LDREXD_A8_436 extends ParseSupport {

	public static final LDREXD_A8_436 INSTANCE = new LDREXD_A8_436();

	@Override
	protected int getRd(int data) {
		return getShiftInt(data, 12, 4);
	}

	@Override
	protected int getRn(int data) {
		return getShiftInt(data, 8, 4);
	}

	@Override
	protected int getRm(int data) {
		return getShiftInt(data, 16, 4);
	}

	@Override
	protected boolean isRmMemory() {
		return true;
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}