/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction;

import brilliant.arm.OpCode.arm.instruction.support.ParseSupport;

@Deprecated
public class LDRHT_A8_448 extends ParseSupport {

	public static final LDRHT_A8_448 INSTANCE = new LDRHT_A8_448();

	public String parse(int data) {
		throw new UnsupportedOperationException("LDRHT no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}