/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction;

import brilliant.arm.OpCode.arm.instruction.support.ParseSupport;

@Deprecated
public class LDRSB_A8_450 extends ParseSupport {

	public static final LDRSB_A8_450 INSTANCE = new LDRSB_A8_450();

	public String parse(int data) {
		throw new UnsupportedOperationException("LDRSB no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}