/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction;

import brilliant.arm.OpCode.arm.instruction.support.ParseSupport;

@Deprecated
public class LDRSH_A8_460 extends ParseSupport {

	public static final LDRSH_A8_460 INSTANCE = new LDRSH_A8_460();

	public String parse(int data) {
		throw new UnsupportedOperationException("LDRSH no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}