/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction;

import brilliant.arm.OpCode.arm.instruction.support.ParseSupport;

@Deprecated
public class MSR_B9_1994 extends ParseSupport {

	public static final MSR_B9_1994 INSTANCE = new MSR_B9_1994();

	@Override
	public String parse(int data) {
		error(data);
		return null;
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}