/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction;

import static brilliant.arm.OpCode.OpUtil.getShiftInt;
import static brilliant.arm.OpCode.OpUtil.parseRegisterList;
import brilliant.arm.OpCode.CondFactory;
import brilliant.arm.OpCode.arm.instruction.support.ParseSupport;

public class PUSH_A8_538 extends ParseSupport {

	public static final PUSH_A8_538 INSTANCE = new PUSH_A8_538();

	@Override
	public String parse(int data) {
		int op = getShiftInt(data, 21, 7);
		if (op == 0b1001001)
			return EncodingA1(data);

		if (op == 0b0101001)
			return EnocdingA2(data);

		return error(data);
	}

	private String EncodingA1(int data) {

		StringBuilder sb = new StringBuilder("PUSH");

		sb.append(CondFactory.parse(getCond(data)));
		sb.append(" {");
		sb.append(parseRegisterList(getShiftInt(data, 0, 16), -1));
		sb.append("}");

		return sb.toString();
	}

	private String EnocdingA2(int data) {
		return null;
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}