/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction;

import brilliant.arm.OpCode.arm.instruction.support.ParseSupport;


@Deprecated
public class SEV_A8_606 extends ParseSupport {

	public static final SEV_A8_606 INSTANCE = new SEV_A8_606();

	public String parse(int data) {
		throw new UnsupportedOperationException("SEV no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}