/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction;

import brilliant.arm.OpCode.arm.instruction.support.ParseSupport;

@Deprecated
public class SMLAL_A8_624 extends ParseSupport {

	public static final SMLAL_A8_624 INSTANCE = new SMLAL_A8_624();

	public String parse(int data) {
		throw new UnsupportedOperationException("SMLAL no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}