/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction;

import brilliant.arm.OpCode.arm.instruction.support.ParseSupport;


@Deprecated
public class SMULBB_A8_644 extends ParseSupport {

	public static final SMULBB_A8_644 INSTANCE = new SMULBB_A8_644();

	public String parse(int data) {
		throw new UnsupportedOperationException("SMLULBB no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}