/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction;

import brilliant.arm.OpCode.arm.instruction.support.ParseSupport;

@Deprecated
public class STM_B9_2008 extends ParseSupport {

	public static final STM_B9_2008 INSTANCE = new STM_B9_2008();

	public String parse(int data) {
		throw new UnsupportedOperationException("STM no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}