/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction;

import brilliant.arm.OpCode.arm.instruction.support.ParseSupport;

@Deprecated
public class STREXH_A8_696 extends ParseSupport {

	public static final STREXH_A8_696 INSTANCE = new STREXH_A8_696();

	public String parse(int data) {
		throw new UnsupportedOperationException("STREXH no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}