/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction;

import brilliant.arm.OpCode.arm.instruction.support.ParseSupport;


@Deprecated
public class STREXD_A8_694 extends ParseSupport {

	public static final STREXD_A8_694 INSTANCE = new STREXD_A8_694();

	public String parse(int data) {
		throw new UnsupportedOperationException("STREXD no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}