/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction;

import brilliant.arm.OpCode.arm.instruction.support.ParseSupport;

@Deprecated
public class STREX_A8_690 extends ParseSupport {

	public static final STREX_A8_690 INSTANCE = new STREX_A8_690();

	public String parse(int data) {
		throw new UnsupportedOperationException("STREX no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}