/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction;

import brilliant.arm.OpCode.arm.instruction.support.ParseSupport;


@Deprecated
public class STREXB_A8_692 extends ParseSupport {

	public static final STREXB_A8_692 INSTANCE = new STREXB_A8_692();

	public String parse(int data) {
		throw new UnsupportedOperationException("STREXB no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}