/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction;

import brilliant.arm.OpCode.arm.instruction.support.ParseSupport;


@Deprecated
public class STRH_A8_702 extends ParseSupport {

	public static final STRH_A8_702 INSTANCE = new STRH_A8_702();

	public String parse(int data) {
		throw new UnsupportedOperationException("STRH no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}