/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction;

import brilliant.arm.OpCode.arm.instruction.support.ParseSupport;


@Deprecated
public class UMLAL_A8_776 extends ParseSupport {

	public static final UMLAL_A8_776 INSTANCE = new UMLAL_A8_776();

	public String parse(int data) {
		throw new UnsupportedOperationException("UMLAL no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}