/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.arm.instruction;

import brilliant.arm.OpCode.arm.instruction.support.ParseSupport;

@Deprecated
public class UMULL_A8_778 extends ParseSupport {

	public static final UMULL_A8_778 INSTANCE = new UMULL_A8_778();

	public String parse(int data) {
		throw new UnsupportedOperationException("UMULL no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}