/*-------------------------------
 Auto Generated By AutoGenetate
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.thumb16.instruction;

import com.marik.arm.OpCode.thumb16.instruction.factory.ParseSupport;
import static com.marik.arm.OpCode.OpUtil.*;

public class ADD_A8_306 extends ParseSupport {

	public static final ADD_A8_306 INSTANCE = new ADD_A8_306();

	@Override
	protected String getOpCode() {
		return null;
	}
	@Override
	protected String getRn(int data) {
		return null;
	}
	@Override
	protected String getRm(int data) {
		return null;
	}

}