/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.thumb16.instruction;

import com.marik.arm.OpCode.thumb16.instruction.factory.ParseSupport;

public class BKPT_A8_346 extends ParseSupport {

	public static final BKPT_A8_346 INSTANCE = new BKPT_A8_346();

	public String parse(int data) {
		throw new UnsupportedOperationException("BKPT no implements");
	}

	@Override
	protected void performExecuteCommand() {
	}

}