/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.thumb16.instruction;

import com.marik.arm.OpCode.thumb16.instruction.factory.ParseSupport;

public class CBZ_A8_356 extends ParseSupport {

	public static final CBZ_A8_356 INSTANCE = new CBZ_A8_356();

	public String parse(int data) {
			throw new UnsupportedOperationException("CBZ no implements");
	}
	@Override
	protected void performExecuteCommand() {
	}

}