/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.thumb16.instruction;

import com.marik.arm.OpCode.thumb16.instruction.factory.ParseSupport;
import static com.marik.arm.OpCode.OpUtil.*;

public class CMP_A8_370 extends ParseSupport {

	public static final CMP_A8_370 INSTANCE = new CMP_A8_370();

	@Override
	protected String getOpCode() {
		return "CMP";
	}

	@Override
	protected String getRn(int data) {
		return parseRegister(getShiftInt(data, 8, 3));
	}

	@Override
	protected String getRm(int data) {
		return "#" + getShiftInt(data, 0, 8);
	}
}