/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.thumb16.instruction;

import com.marik.arm.OpCode.thumb16.instruction.factory.ParseSupport;

public class LDRH_A8_440 extends ParseSupport {

	public static final LDRH_A8_440 INSTANCE = new LDRH_A8_440();

	public String parse(int data) {
			throw new UnsupportedOperationException("LDRH no implements");
	}
	@Override
	protected void performExecuteCommand() {
	}

}