/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.thumb16.instruction;

import com.marik.arm.OpCode.thumb16.instruction.factory.ParseSupport;

@Deprecated
public class LDRH_A8_446 extends ParseSupport {

	public static final LDRH_A8_446 INSTANCE = new LDRH_A8_446();

	public String parse(int data) {
		throw new UnsupportedOperationException("LDRH no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}