/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.thumb16.instruction;

import static com.marik.arm.OpCode.OpUtil.getShiftInt;
import static com.marik.arm.OpCode.OpUtil.parseRegister;

import com.marik.arm.OpCode.thumb16.instruction.factory.ParseSupport;

public class MOV_A8_484 extends ParseSupport {

	public static final MOV_A8_484 INSTANCE = new MOV_A8_484();

	@Override
	protected String getOpCode() {
		return "MOVS";
	}

	@Override
	protected String getRn(int data) {
		return parseRegister(getShiftInt(data, 8, 3));
	}

	@Override
	protected String getRm(int data) {
		return "#" + getShiftInt(data, 0, 8);
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}