/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.thumb16.instruction;

import com.marik.arm.OpCode.thumb16.instruction.factory.ParseSupport;

@Deprecated
public class SETEND_A8_604 extends ParseSupport {

	public static final SETEND_A8_604 INSTANCE = new SETEND_A8_604();

	public String parse(int data) {
		throw new UnsupportedOperationException("SETEND no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}