/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.thumb16.instruction;

import com.marik.arm.OpCode.thumb16.instruction.factory.ParseSupport;

public class SEV_A8_606 extends ParseSupport {

	public static final SEV_A8_606 INSTANCE = new SEV_A8_606();

	public String parse(int data) {
			throw new UnsupportedOperationException("SEV no implements");
	}
	@Override
	protected void performExecuteCommand() {
	}

}