/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.thumb16.instruction;

import com.marik.arm.OpCode.thumb16.instruction.factory.ParseSupport;

public class STRH_A8_698 extends ParseSupport {

	public static final STRH_A8_698 INSTANCE = new STRH_A8_698();

	public String parse(int data) {
			throw new UnsupportedOperationException("STRH no implements");
	}
	@Override
	protected void performExecuteCommand() {
	}

}