/*-------------------------------
 Auto Generated By AutoGenetate
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.thumb16.instruction;

import com.marik.arm.OpCode.thumb16.instruction.factory.ParseSupport;
import static com.marik.arm.OpCode.OpUtil.*;

public class SUB_A8_708 extends ParseSupport {

	public static final SUB_A8_708 INSTANCE = new SUB_A8_708();

	@Override
	protected String getOpCode() {
		return null;
	}
	@Override
	protected String getRn(int data) {
		return null;
	}
	@Override
	protected String getRm(int data) {
		return null;
	}

}