/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.thumb16.instruction;

import com.marik.arm.OpCode.thumb16.instruction.factory.ParseSupport;

@Deprecated
public class SXTB_A8_730 extends ParseSupport {

	public static final SXTB_A8_730 INSTANCE = new SXTB_A8_730();

	public String parse(int data) {
		throw new UnsupportedOperationException("SXTB no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}
}