/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.thumb16.instruction;

import com.marik.arm.OpCode.thumb16.instruction.factory.ParseSupport;

public class UXTH_A8_816 extends ParseSupport {

	public static final UXTH_A8_816 INSTANCE = new UXTH_A8_816();

	public String parse(int data) {
			throw new UnsupportedOperationException("UXTH no implements");
	}
	@Override
	protected void performExecuteCommand() {
	}

}