/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.thumb16.instruction;

import com.marik.arm.OpCode.thumb16.instruction.factory.ParseSupport;

@Deprecated
public class WFE_A8_1104 extends ParseSupport {

	public static final WFE_A8_1104 INSTANCE = new WFE_A8_1104();

	public String parse(int data) {
		throw new UnsupportedOperationException("WFE no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}