/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.thumb16.instruction;

import com.marik.arm.OpCode.thumb16.instruction.factory.ParseSupport;

public class WFI_A8_1106 extends ParseSupport {

	public static final WFI_A8_1106 INSTANCE = new WFI_A8_1106();

	public String parse(int data) {
			throw new UnsupportedOperationException("WFI no implements");
	}
	@Override
	protected void performExecuteCommand() {
	}

}