/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.arm.instruction;

import com.marik.arm.OpCode.arm.instruction.factory.ParseSupport;
import static com.marik.vm.OS.*;
import static com.marik.vm.Register.*;
import static com.marik.arm.OpCode.OpUtil.*;

public class AND_A8_324 extends ParseSupport {

	public static final AND_A8_324 INSTANCE = new AND_A8_324();

	@Override
	protected String getOpCode() {
		return null;
	}
	@Override
	protected String getRn(int data) {
		return null;
	}
	@Override
	protected String getRm(int data) {
		return null;
	}
	@Override
	public void performExecuteCommand(int data) {
	}

}