/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.arm.instruction;

import com.marik.arm.OpCode.arm.instruction.support.ParseSupport;


@Deprecated
public class BKPT_A8_346 extends ParseSupport {

	public static final BKPT_A8_346 INSTANCE = new BKPT_A8_346();

	public String parse(int data) {
		throw new UnsupportedOperationException("BKPT no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}