/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.arm.instruction;

import com.marik.arm.OpCode.arm.instruction.factory.ParseSupport;

@Deprecated
public class DBG_A8_377 extends ParseSupport {

	public static final DBG_A8_377 INSTANCE = new DBG_A8_377();

	public String parse(int data) {
		throw new UnsupportedOperationException("DBG no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}