/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.arm.instruction;

import com.marik.arm.OpCode.arm.instruction.support.ParseSupport;


@Deprecated
public class LDC_A8_394 extends ParseSupport {

	public static final LDC_A8_394 INSTANCE = new LDC_A8_394();

	public String parse(int data) {
			throw new UnsupportedOperationException("LDC no implements");
	}
	@Override
	public void performExecuteCommand(int data) {
	}

}