/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.arm.instruction;

import com.marik.arm.OpCode.arm.instruction.support.ParseSupport;


@Deprecated
public class LDM_B9_1988 extends ParseSupport {

	public static final LDM_B9_1988 INSTANCE = new LDM_B9_1988();

	public String parse(int data) {
		throw new UnsupportedOperationException("LDM no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}