/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.arm.instruction;

import com.marik.arm.OpCode.arm.instruction.factory.ParseSupport;

/**
 * @author Yoogurt This class is an other implements of {@link LDR_A8_408}
 */
public class LDR_A8_410 extends ParseSupport {

	public static final LDR_A8_410 INSTANCE = new LDR_A8_410();

	@Override
	public String parse(int data) {
		return LDR_A8_408.INSTANCE.parse(data);
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}