/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.arm.instruction;

import com.marik.arm.OpCode.arm.instruction.factory.ParseSupport;

@Deprecated
public class LDREX_A8_432 extends ParseSupport {

	public static final LDREX_A8_432 INSTANCE = new LDREX_A8_432();

	public String parse(int data) {
			throw new UnsupportedOperationException("LDREX no implements");
	}
	@Override
	public void performExecuteCommand(int data) {
	}

}