/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.arm.instruction;

import com.marik.arm.OpCode.arm.instruction.support.ParseSupport;


@Deprecated
public class LDREXD_A8_436 extends ParseSupport {

	public static final LDREXD_A8_436 INSTANCE = new LDREXD_A8_436();

	public String parse(int data) {
		throw new UnsupportedOperationException("LDREXD no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}