/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.arm.instruction;

import com.marik.arm.OpCode.arm.instruction.factory.ParseSupport;

@Deprecated
public class LDREXB_A8_434 extends ParseSupport {

	public static final LDREXB_A8_434 INSTANCE = new LDREXB_A8_434();

	public String parse(int data) {
		throw new UnsupportedOperationException("LDREXB no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}