/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.arm.instruction;

import com.marik.arm.OpCode.arm.instruction.factory.ParseSupport;

@Deprecated
public class LDREXH_A8_438 extends ParseSupport {

	public static final LDREXH_A8_438 INSTANCE = new LDREXH_A8_438();

	public String parse(int data) {
		throw new UnsupportedOperationException("LDREXH no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}