/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.arm.instruction;

import com.marik.arm.OpCode.arm.instruction.factory.ParseSupport;

@Deprecated
public class LDRH_A8_442 extends ParseSupport {

	public static final LDRH_A8_442 INSTANCE = new LDRH_A8_442();

	public String parse(int data) {
		throw new UnsupportedOperationException("LDRH no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}