/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.arm.instruction;

import com.marik.arm.OpCode.arm.instruction.support.ParseSupport;


@Deprecated
public class LDRH_A8_444 extends ParseSupport {

	public static final LDRH_A8_444 INSTANCE = new LDRH_A8_444();

	public String parse(int data) {
		throw new UnsupportedOperationException("LDRH no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}