/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.arm.instruction;

import com.marik.arm.OpCode.arm.instruction.support.ParseSupport;


@Deprecated
public class LDRSB_A8_452 extends ParseSupport {

	public static final LDRSB_A8_452 INSTANCE = new LDRSB_A8_452();

	public String parse(int data) {
		throw new UnsupportedOperationException("LDRSB no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}