/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.arm.instruction;

import com.marik.arm.OpCode.arm.instruction.factory.ParseSupport;

@Deprecated
public class LDRSBT_A8_456 extends ParseSupport {

	public static final LDRSBT_A8_456 INSTANCE = new LDRSBT_A8_456();

	public String parse(int data) {
		throw new UnsupportedOperationException("LDRSBT no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}