/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.arm.instruction;

import com.marik.arm.OpCode.arm.instruction.support.ParseSupport;


@Deprecated
public class LDRSHT_A8_464 extends ParseSupport {

	public static final LDRSHT_A8_464 INSTANCE = new LDRSHT_A8_464();

	public String parse(int data) {
		throw new UnsupportedOperationException("LDRSHT no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}