/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.arm.instruction;

import com.marik.arm.OpCode.arm.instruction.factory.ParseSupport;

@Deprecated
public class LDRSH_A8_458 extends ParseSupport {

	public static final LDRSH_A8_458 INSTANCE = new LDRSH_A8_458();

	public String parse(int data) {
			throw new UnsupportedOperationException("LDRSH no implements");
	}
	@Override
	public void performExecuteCommand(int data) {
	}

}