/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.arm.instruction;

import com.marik.arm.OpCode.arm.instruction.factory.ParseSupport;

@Deprecated
public class MCR_A8_476 extends ParseSupport {

	public static final MCR_A8_476 INSTANCE = new MCR_A8_476();

	public String parse(int data) {
			throw new UnsupportedOperationException("MCR no implements");
	}
	@Override
	public void performExecuteCommand(int data) {
	}

}