/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.arm.instruction;

import com.marik.arm.OpCode.arm.instruction.support.ParseSupport;


@Deprecated
public class MCRR_A8_478 extends ParseSupport {

	public static final MCRR_A8_478 INSTANCE = new MCRR_A8_478();

	public String parse(int data) {
			throw new UnsupportedOperationException("MCRR no implements");
	}
	@Override
	public void performExecuteCommand(int data) {
	}

}