/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.arm.instruction;

import com.marik.arm.OpCode.arm.instruction.factory.ParseSupport;

@Deprecated
public class MRC_A8_492 extends ParseSupport {

	public static final MRC_A8_492 INSTANCE = new MRC_A8_492();

	public String parse(int data) {
			throw new UnsupportedOperationException("MRC no implements");
	}
	@Override
	public void performExecuteCommand(int data) {
	}

}