/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.arm.instruction;

import com.marik.arm.OpCode.arm.instruction.factory.ParseSupport;

@Deprecated
public class MRRC_A8_494 extends ParseSupport {

	public static final MRRC_A8_494 INSTANCE = new MRRC_A8_494();

	public String parse(int data) {
			throw new UnsupportedOperationException("MRRC no implements");
	}
	@Override
	public void performExecuteCommand(int data) {
	}

}