/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.arm.instruction;

import com.marik.arm.OpCode.arm.instruction.factory.ParseSupport;

@Deprecated
public class MRS_A8_496 extends ParseSupport {

	public static final MRS_A8_496 INSTANCE = new MRS_A8_496();

	@Override
	public String parse(int data) {
		error(data);
		return null;
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}