/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.arm.instruction;

import com.marik.arm.OpCode.arm.instruction.support.ParseSupport;


@Deprecated
public class MSR_B9_1998 extends ParseSupport {

	public static final MSR_B9_1998 INSTANCE = new MSR_B9_1998();

	@Override
	public String parse(int data) {
		error(data);
		return null;
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}