/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.arm.instruction;

import com.marik.arm.OpCode.arm.instruction.factory.ParseSupport;

import static com.marik.vm.OS.*;
import static com.marik.vm.Register.*;
import static com.marik.arm.OpCode.OpUtil.*;

@Deprecated
public class MSR_A8_500 extends ParseSupport {

	public static final MSR_A8_500 INSTANCE = new MSR_A8_500();

	@Override
	public String parse(int data) {
		error(data);
		return null;
	}
	@Override
	public void performExecuteCommand(int data) {
	}

}