/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.arm.instruction;

import com.marik.arm.OpCode.arm.instruction.support.ParseSupport;


@Deprecated
public class SMLALBB_A8_626 extends ParseSupport {

	public static final SMLALBB_A8_626 INSTANCE = new SMLALBB_A8_626();

	public String parse(int data) {
		throw new UnsupportedOperationException("SMLALBB no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}