/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.arm.instruction;

import com.marik.arm.OpCode.arm.instruction.factory.ParseSupport;

@Deprecated
public class SMLAWB_A8_630 extends ParseSupport {

	public static final SMLAWB_A8_630 INSTANCE = new SMLAWB_A8_630();

	public String parse(int data) {
			throw new UnsupportedOperationException("SMLAWB no implements");
	}
	@Override
	public void performExecuteCommand(int data) {
	}

}