/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.arm.instruction;

import com.marik.arm.OpCode.arm.instruction.factory.ParseSupport;

@Deprecated
public class SMLABB_A8_620 extends ParseSupport {

	public static final SMLABB_A8_620 INSTANCE = new SMLABB_A8_620();

	public String parse(int data) {
			throw new UnsupportedOperationException("SMLABB no implements");
	}
	@Override
	public void performExecuteCommand(int data) {
	}

}