/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.arm.instruction;

import com.marik.arm.OpCode.arm.instruction.factory.ParseSupport;

@Deprecated
public class SMLULBB_A8_644 extends ParseSupport {

	public static final SMLULBB_A8_644 INSTANCE = new SMLULBB_A8_644();

	public String parse(int data) {
			throw new UnsupportedOperationException("SMLULBB no implements");
	}
	@Override
	public void performExecuteCommand(int data) {
	}

}