/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.arm.instruction;

import com.marik.arm.OpCode.arm.instruction.factory.ParseSupport;

@Deprecated
public class SMULWB_A8_648 extends ParseSupport {

	public static final SMULWB_A8_648 INSTANCE = new SMULWB_A8_648();

	public String parse(int data) {
			throw new UnsupportedOperationException("SMULWB no implements");
	}
	@Override
	public void performExecuteCommand(int data) {
	}

}