/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.arm.instruction;

import com.marik.arm.OpCode.arm.instruction.factory.ParseSupport;

@Deprecated
public class SMULL_A8_646 extends ParseSupport {

	public static final SMULL_A8_646 INSTANCE = new SMULL_A8_646();

	public String parse(int data) {
		throw new UnsupportedOperationException("SMULL no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}