/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.arm.instruction;

import com.marik.arm.OpCode.arm.instruction.factory.ParseSupport;

@Deprecated
public class STC_A8_662 extends ParseSupport {

	public static final STC_A8_662 INSTANCE = new STC_A8_662();

	public String parse(int data) {
			throw new UnsupportedOperationException("STC no implements");
	}
	@Override
	public void performExecuteCommand(int data) {
	}

}