/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.arm.instruction;

import com.marik.arm.OpCode.arm.instruction.factory.ParseSupport;

@Deprecated
public class STRD_A8_686 extends ParseSupport {

	public static final STRD_A8_686 INSTANCE = new STRD_A8_686();

	public String parse(int data) {
			throw new UnsupportedOperationException("STRD no implements");
	}
	@Override
	public void performExecuteCommand(int data) {
	}

}