/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.arm.instruction;

import com.marik.arm.OpCode.arm.instruction.factory.ParseSupport;

@Deprecated
public class STRHT_A8_704 extends ParseSupport {

	public static final STRHT_A8_704 INSTANCE = new STRHT_A8_704();

	public String parse(int data) {
			throw new UnsupportedOperationException("STRHT no implements");
	}
	@Override
	public void performExecuteCommand(int data) {
	}

}