/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.arm.instruction;

import com.marik.arm.OpCode.arm.instruction.factory.ParseSupport;

@Deprecated
public class UMAAL_A8_774 extends ParseSupport {

	public static final UMAAL_A8_774 INSTANCE = new UMAAL_A8_774();

	public String parse(int data) {
		throw new UnsupportedOperationException("UMAAL no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}