/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.arm.instruction;

import com.marik.arm.OpCode.arm.instruction.factory.ParseSupport;

@Deprecated
public class YIELD_A8_1108 extends ParseSupport {

	public static final YIELD_A8_1108 INSTANCE = new YIELD_A8_1108();

	public String parse(int data) {
		throw new UnsupportedOperationException("YIELD no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}