/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.thumb.instruction32;

import com.marik.arm.OpCode.thumb.instruction32.support.ParseSupport;

@Deprecated
public class BFC_A8_336 extends ParseSupport {

	public static final BFC_A8_336 INSTANCE = new BFC_A8_336();

	@Override
	protected String getOpCode(int data) {
		return "BFC.W";
	}
	@Override
	public void performExecuteCommand(int data) {
	}

}