/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.thumb.instruction32;

import com.marik.arm.OpCode.thumb.instruction32.support.ParseSupport;

import static com.marik.vm.OS.*;
import static com.marik.vm.Register.*;
import static com.marik.arm.OpCode.OpUtil.*;

public class LDRB_A8_420 extends ParseSupport {

	public static final LDRB_A8_420 INSTANCE = new LDRB_A8_420();

	@Override
	public String parse(int data) {

		StringBuilder sb = new StringBuilder("LDRB.W ");
		int Rt = getShiftInt(data, 12, 4);
		int imm12 = getShiftInt(data, 0, 12);
		boolean add = getShiftInt(data, 23, 1) == 0b1;
		sb.append(parseRegister(Rt));
		sb.append(" , [PC , #");
		if (!add)
			sb.append("-");
		sb.append(imm12);
		sb.append("]");

		return sb.toString();

	}

	@Override
	public void performExecuteCommand(int data) {
	}

}