/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.thumb.instruction32;

import com.marik.arm.OpCode.thumb.instruction32.support.ParseSupport;

import static com.marik.vm.OS.*;
import static com.marik.vm.Register.*;
import static com.marik.arm.OpCode.OpUtil.*;

public class LDRSB_A8_454 extends ParseSupport {

	public static final LDRSB_A8_454 INSTANCE = new LDRSB_A8_454();

	@Override
	public String parse(int data) {

		StringBuilder sb = new StringBuilder("LDRSB.W ");
		int Rt = getShiftInt(data, 12, 4);
		int Rn = getShiftInt(data, 16, 4);
		int Rm = getShiftInt(data, 0, 4);
		int imm2 = getShiftInt(data, 4, 2);

		sb.append(parseRegister(Rt));
		sb.append(" , [");
		sb.append(parseRegister(Rn));
		sb.append(" , ");
		sb.append(parseRegister(Rm));
		sb.append(" , LSL #");
		sb.append(imm2);
		sb.append("]");

		return sb.toString();
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}