/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.thumb.instruction32;

import com.marik.arm.OpCode.thumb.instruction32.support.ParseSupport;

@Deprecated
public class PLD_A8_526 extends ParseSupport {

	public static final PLD_A8_526 INSTANCE = new PLD_A8_526();

	@Override
	protected String getOpCode(int data) {
		return "PLD";
	}
	@Override
	public void performExecuteCommand(int data) {
	}

}