/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.thumb.instruction32;

import com.marik.arm.OpCode.thumb.instruction32.support.ParseSupport;

@Deprecated
public class SBFX_A8_598 extends ParseSupport {

	public static final SBFX_A8_598 INSTANCE = new SBFX_A8_598();

	@Override
	protected String getOpCode(int data) {
		return "SBFX.W";
	}
	@Override
	public void performExecuteCommand(int data) {
	}

}