/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.thumb.instruction32;

import com.marik.arm.OpCode.thumb.instruction32.support.ParseSupport;

@Deprecated
public class SRS_B9_2004 extends ParseSupport {

	public static final SRS_B9_2004 INSTANCE = new SRS_B9_2004();

	@Override
	protected String getOpCode(int data) {
		return "SRS.W";
	}
	@Override
	public void performExecuteCommand(int data) {
	}

}