/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.thumb.instruction32;

import com.marik.arm.OpCode.thumb.instruction32.support.ParseSupport;

@Deprecated
public class SSAT16_A8_654 extends ParseSupport {

	public static final SSAT16_A8_654 INSTANCE = new SSAT16_A8_654();

	@Override
	protected String getOpCode(int data) {
		return "SSAT16";
	}
	@Override
	public void performExecuteCommand(int data) {
	}

}