/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.thumb.instruction32;

import com.marik.arm.OpCode.thumb.instruction32.support.ParseSupport;

@Deprecated
public class SSAT_A8_652 extends ParseSupport {

	public static final SSAT_A8_652 INSTANCE = new SSAT_A8_652();

	@Override
	protected String getOpCode(int data) {
		return "SSAT.W";
	}
	@Override
	public void performExecuteCommand(int data) {
	}

}