/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.thumb.instruction32;

import com.marik.arm.OpCode.thumb.instruction32.support.ParseSupport;

@Deprecated
public class SUBS_B9_2010 extends ParseSupport {

	public static final SUBS_B9_2010 INSTANCE = new SUBS_B9_2010();

	@Override
	protected String getOpCode(int data) {
		return "SUBS.W";
	}
	@Override
	public void performExecuteCommand(int data) {
	}

}