/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.thumb.instruction32;

import com.marik.arm.OpCode.thumb.instruction32.support.ParseSupport;

@Deprecated
public class UBFX_A8_756 extends ParseSupport {

	public static final UBFX_A8_756 INSTANCE = new UBFX_A8_756();

	@Override
	protected String getOpCode(int data) {
		return "UBFX.W";
	}
	@Override
	public void performExecuteCommand(int data) {
	}

}