/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.thumb.instruction32;

import com.marik.arm.OpCode.thumb.instruction32.support.ParseSupport;

@Deprecated
public class USAT_A8_796 extends ParseSupport {

	public static final USAT_A8_796 INSTANCE = new USAT_A8_796();

	@Override
	protected String getOpCode(int data) {
		return "USAT.W";
	}
	@Override
	public void performExecuteCommand(int data) {
	}

}