/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.thumb.instruction32;

import com.marik.arm.OpCode.thumb.instruction32.support.ParseSupport;

@Deprecated
public class USAT16_A8_798 extends ParseSupport {

	public static final USAT16_A8_798 INSTANCE = new USAT16_A8_798();

	@Override
	protected String getOpCode(int data) {
		return "USAT16.W";
	}
	@Override
	public void performExecuteCommand(int data) {
	}

}