/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction16;

import static brilliant.arm.OpCode.factory.OpUtil.getShiftInt;
import static brilliant.arm.OpCode.factory.OpUtil.parseRegister;
import brilliant.arm.OpCode.factory.OpUtil;
import brilliant.arm.OpCode.thumb.instruction16.support.ParseSupport;
import brilliant.elf.vm.Register;

public class ADD_A8_310 extends ParseSupport {

	public static final ADD_A8_310 INSTANCE = new ADD_A8_310();

	@Override
	public String parse(int data) {

		int head = getShiftInt(data, 9, 7);
		if (head == 0b0001100)
			return super.parse(data);

		head = getShiftInt(data, 8, 8);
		if (head == 0b01000100)
			return EncodingT2(data);

		return error(data);
	}

	private String EncodingT2(int data) {
		int DN = getShiftInt(data, 7, 1);
		int Rm = getShiftInt(data, 3, 4);
		int Rdn = getShiftInt(data, 0, 3);

		int Rd = DN << 3 | Rdn;

		StringBuilder sb = new StringBuilder("ADD ");
		sb.append(parseRegister(Rd)).append(" , ");
		sb.append(parseRegister(Rm));

		if (Rm == OpUtil.PC)
			if (Register.PC > 0)
				sb.append(" @" + Integer.toHexString(Register.PC));

		return sb.toString();
	}

	@Override
	protected String getOpCode(int data) {
		return "ADDS";
	}

	@Override
	protected String getRn(int data) {
		return parseRegister(getShiftInt(data, 0, 3));
	}

	@Override
	protected String getRm(int data) {
		return parseRegister(getShiftInt(data, 3, 3)) + " , "
				+ parseRegister(getShiftInt(data, 6, 3));
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}
