/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction16;

import static brilliant.arm.OpCode.OpUtil.getShiftInt;
import static brilliant.arm.OpCode.OpUtil.parseRegister;
import brilliant.arm.OpCode.thumb.instruction16.support.ParseSupport;

public class BLX_A8_350 extends ParseSupport {

	public static final BLX_A8_350 INSTANCE = new BLX_A8_350();

	@Override
	protected String getOpCode(int data) {
		return "BLX";
	}

	@Override
	protected String getRn(int data) {
		return parseRegister(getShiftInt(data, 3, 4));
	}

	@Override
	protected String getRm(int data) {
		return null;
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}