/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction16;

import static brilliant.arm.OpCode.OpUtil.getShiftInt;
import static brilliant.arm.OpCode.OpUtil.parseRegister;
import brilliant.arm.OpCode.thumb.instruction16.support.ParseSupport;

public class BX_A8_352 extends ParseSupport {

	public static final BX_A8_352 INSTANCE = new BX_A8_352();

	@Override
	protected String getOpCode(int data) {
		return "BX";
	}

	@Override
	protected String getRn(int data) {
		return parseRegister(getShiftInt(data, 3, 4));
	}

	@Override
	protected String getRm(int data) {
		return null;
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}