/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction16;

import brilliant.arm.OpCode.thumb.instruction16.support.ParseSupport;


@Deprecated
public class CBZ_A8_356 extends ParseSupport {

	public static final CBZ_A8_356 INSTANCE = new CBZ_A8_356();

	public String parse(int data) {
		throw new UnsupportedOperationException("CBZ no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}