/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction16;

import brilliant.arm.OpCode.thumb.instruction16.support.ParseSupport;


@Deprecated
public class CPS_B9_1978 extends ParseSupport {

	public static final CPS_B9_1978 INSTANCE = new CPS_B9_1978();

	public String parse(int data) {
		throw new UnsupportedOperationException("CPS no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}