/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction16;

import static brilliant.arm.OpCode.OpUtil.getShiftInt;
import static brilliant.arm.OpCode.OpUtil.isRigisterInRegisterList;
import static brilliant.arm.OpCode.OpUtil.parseRegister;
import static brilliant.arm.OpCode.OpUtil.parseRegisterList;
import brilliant.arm.OpCode.thumb.instruction16.support.ParseSupport;

public class LDM_A8_396 extends ParseSupport {
	public static final LDM_A8_396 INSTANCE = new LDM_A8_396();

	@Override
	protected String getOpCode(int data) {
		return "LDM";
	}

	@Override
	protected String getRn(int data) {
		int Rn = getShiftInt(data, 8, 3);
		int registerList = getShiftInt(data, 0, 8);

		if (!isRigisterInRegisterList(Rn, registerList))
			return parseRegister(Rn) + "!";
		return parseRegister(Rn);
	}

	@Override
	protected String getRm(int data) {
		return parseRegisterList(getShiftInt(data, 0, 8),
				getShiftInt(data, 8, 3));
	}

	@Override
	protected boolean isRmRegisterList() {
		return true;
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}
