/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction16;

import static brilliant.arm.OpCode.factory.OpUtil.getShiftInt;
import static brilliant.arm.OpCode.factory.OpUtil.parseRegister;
import static brilliant.arm.OpCode.factory.OpUtil.align;
import brilliant.arm.OpCode.thumb.instruction16.support.ParseSupport;
import brilliant.elf.vm.Register;

/**
 * load from memory , <label> = [PC + zeroExtend(imm8:00)]
 */
public class LDR_A8_410 extends ParseSupport {

	public static final LDR_A8_410 INSTANCE = new LDR_A8_410();

	@Override
	protected String getOpCode(int data) {
		return "LDR";
	}

	@Override
	protected String getRn(int data) {
		return parseRegister(getShiftInt(data, 8, 3));
	}

	@Override
	protected String getRm(int data) {
		return "#" + (getShiftInt(data, 0, 8) << 2);
	}

	@Override
	protected String getComment(int data) {
		if (Register.PC < 0)
			return null;
		return "@"
				+ Integer.toHexString(align(Register.PC, 4) 
						+ (getShiftInt(data, 0, 8) << 2));
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}
