/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction16;

import brilliant.arm.OpCode.thumb.instruction16.support.ParseSupport;

@Deprecated
public class LDRB_A8_416 extends ParseSupport {

	public static final LDRB_A8_416 INSTANCE = new LDRB_A8_416();

	public String parse(int data) {
		throw new UnsupportedOperationException("LDRB no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}