/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction16;

import brilliant.arm.OpCode.thumb.instruction16.support.ParseSupport;


@Deprecated
public class LDRH_A8_440 extends ParseSupport {

	public static final LDRH_A8_440 INSTANCE = new LDRH_A8_440();

	public String parse(int data) {
		throw new UnsupportedOperationException("LDRH no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}