/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction16;

import brilliant.arm.OpCode.thumb.instruction16.support.ParseSupport;


@Deprecated
public class LDRSH_A8_462 extends ParseSupport {

	public static final LDRSH_A8_462 INSTANCE = new LDRSH_A8_462();

	public String parse(int data) {
		throw new UnsupportedOperationException("LDRSH no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}