/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction16;

import brilliant.arm.OpCode.thumb.instruction16.support.ParseSupport;

@Deprecated
public class LDRSB_A8_454 extends ParseSupport {

	public static final LDRSB_A8_454 INSTANCE = new LDRSB_A8_454();

	public String parse(int data) {
		throw new UnsupportedOperationException("LDRSB no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}