/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction16;

import static brilliant.arm.OpCode.factory.OpUtil.getShiftInt;
import static brilliant.arm.OpCode.factory.OpUtil.parseRegister;
import brilliant.arm.OpCode.thumb.instruction16.support.ParseSupport;

public class LSL_A8_468 extends ParseSupport {

	public static final LSL_A8_468 INSTANCE = new LSL_A8_468();

	@Override
	public String parse(int data) {

		if (getShiftInt(data, 6, 5) == 0b00000)
			return MOV_A8_486.INSTANCE.parse(data);

		return super.parse(data);
	}

	@Override
	protected String getOpCode(int data) {
		return "LSLS";
	}

	@Override
	protected String getRn(int data) {
		return parseRegister(getShiftInt(data, 0, 3));
	}

	@Override
	protected String getRm(int data) {
		return parseRegister(getShiftInt(data, 3, 3)) + " , #"
				+ getShiftInt(data, 6, 5);
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}