/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction16;

import static brilliant.arm.OpCode.OpUtil.getShiftInt;
import static brilliant.arm.OpCode.OpUtil.parseRegisterList;
import brilliant.arm.OpCode.thumb.instruction16.support.ParseSupport;

public class POP_A8_534 extends ParseSupport {

	public static final POP_A8_534 INSTANCE = new POP_A8_534();

	@Override
	public String parse(int data) {
		int M = getShiftInt(data, 8, 1);
		int registerList = getShiftInt(data, 0, 7);

		StringBuilder sb = new StringBuilder("POP ");
		sb.append("{");

		sb.append(parseRegisterList(registerList, -1));
		if (M == 1)
			sb.append(" , PC");
		sb.append("}");

		return sb.toString();
	}

	@Override
	protected String getOpCode(int data) {
		return null;
	}

	@Override
	protected String getRn(int data) {
		return null;
	}

	@Override
	protected String getRm(int data) {
		return null;
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}
