/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction16;

import static brilliant.arm.OpCode.factory.OpUtil.getShiftInt;
import static brilliant.arm.OpCode.factory.OpUtil.parseRegisterList;
import brilliant.arm.OpCode.thumb.instruction16.support.ParseSupport;

public class PUSH_A8_538 extends ParseSupport {

	public static final PUSH_A8_538 INSTANCE = new PUSH_A8_538();

	@Override
	public String parse(int data) {

		int M = getShiftInt(data, 8, 1);
		int registerList = getShiftInt(data, 0, 8);

		StringBuilder sb = new StringBuilder("PUSH ");

		sb.append("{");
		if (registerList != 0b00000000) {
			sb.append(parseRegisterList(registerList, -1));
		}
		if (M == 1) {
			if (registerList != 0b00000000)
				sb.append(" , ");
			sb.append("LR");
		}
		sb.append("}");

		return sb.toString();
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}
