/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction16;

import brilliant.arm.OpCode.thumb.instruction16.support.ParseSupport;

@Deprecated
public class REV16_A8_564 extends ParseSupport {

	public static final REV16_A8_564 INSTANCE = new REV16_A8_564();

	public String parse(int data) {
		throw new UnsupportedOperationException("REV16 no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}