/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction16;

import brilliant.arm.OpCode.thumb.instruction16.support.ParseSupport;

@Deprecated
public class REVSH_A8_566 extends ParseSupport {

	public static final REVSH_A8_566 INSTANCE = new REVSH_A8_566();

	public String parse(int data) {
		throw new UnsupportedOperationException("REVSH no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}