/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction16;

import brilliant.arm.OpCode.thumb.instruction16.support.ParseSupport;


@Deprecated
public class SETEND_A8_604 extends ParseSupport {

	public static final SETEND_A8_604 INSTANCE = new SETEND_A8_604();

	public String parse(int data) {
		throw new UnsupportedOperationException("SETEND no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}