/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction16;

import brilliant.arm.OpCode.thumb.instruction16.support.ParseSupport;


@Deprecated
public class STRB_A8_682 extends ParseSupport {

	public static final STRB_A8_682 INSTANCE = new STRB_A8_682();

	public String parse(int data) {
		throw new UnsupportedOperationException("STRB no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}