/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction16;

import brilliant.arm.OpCode.thumb.instruction16.support.ParseSupport;

@Deprecated
public class SXTH_A8_734 extends ParseSupport {

	public static final SXTH_A8_734 INSTANCE = new SXTH_A8_734();

	public String parse(int data) {
		throw new UnsupportedOperationException("SXTH no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}