/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package brilliant.arm.OpCode.thumb.instruction16;

import brilliant.arm.OpCode.thumb.instruction16.support.ParseSupport;

@Deprecated
public class WFE_A8_1104 extends ParseSupport {

	public static final WFE_A8_1104 INSTANCE = new WFE_A8_1104();

	public String parse(int data) {
		throw new UnsupportedOperationException("WFE no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}