/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.thumb.instruction16;

import static com.marik.arm.OpCode.OpUtil.getShiftInt;
import static com.marik.arm.OpCode.OpUtil.parseRegister;

import com.marik.arm.OpCode.thumb.instruction16.support.ParseSupport;

public class ASR_A8_330 extends ParseSupport {

	public static final ASR_A8_330 INSTANCE = new ASR_A8_330();

	@Override
	protected String getOpCode(int data) {
		return "ASRS";
	}

	@Override
	protected String getRn(int data) {
		return parseRegister(getShiftInt(data, 0, 3));
	}

	@Override
	protected String getRm(int data) {
		int imm5 = getShiftInt(data, 6, 5);
		if (imm5 == 0)
			imm5 = 0x20;
		return parseRegister(getShiftInt(data, 3, 3)) + " , #" + imm5;
	}

	@Override
	public void performExecuteCommand(int data) {
	}
}