/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.thumb.instruction16;

import com.marik.arm.OpCode.thumb.instruction16.support.ParseSupport;


public class NOP_A8_510 extends ParseSupport {

	public static final NOP_A8_510 INSTANCE = new NOP_A8_510();

	@Override
	protected String getOpCode(int data) {
		return "NOP";
	}

	@Override
	protected String getRn(int data) {
		return "";
	}

	@Override
	protected String getRm(int data) {
		return null;
	}

	@Override
	public void performExecuteCommand(int data) {
	}
}