/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.thumb.instruction16;

import com.marik.arm.OpCode.thumb.instruction16.support.ParseSupport;


@Deprecated
public class REV_A8_562 extends ParseSupport {

	public static final REV_A8_562 INSTANCE = new REV_A8_562();

	public String parse(int data) {
		throw new UnsupportedOperationException("REV no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}