/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.thumb.instruction16;

import com.marik.arm.OpCode.thumb.instruction16.support.ParseSupport;


@Deprecated
public class STRB_A8_678 extends ParseSupport {

	public static final STRB_A8_678 INSTANCE = new STRB_A8_678();

	public String parse(int data) {
		throw new UnsupportedOperationException("STRB no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}

}