/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.thumb.instruction16;

import static com.marik.arm.OpCode.OpUtil.getShiftInt;

import com.marik.arm.OpCode.thumb.instruction16.support.ParseSupport;

public class SUB_A8_716 extends ParseSupport {

	public static final SUB_A8_716 INSTANCE = new SUB_A8_716();

	@Override
	protected String getOpCode(int data) {
		return "SUB";
	}

	@Override
	protected String getRn(int data) {
		return "SP";
	}

	@Override
	protected String getRm(int data) {
		return "SP , #" + ((getShiftInt(data, 0, 7) << 2));
	}

	@Override
	public void performExecuteCommand(int data) {
	}
}
