/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.thumb.instruction16;

import com.marik.arm.OpCode.thumb.instruction16.support.ParseSupport;


@Deprecated
public class SVC_A8_720 extends ParseSupport {

	public static final SVC_A8_720 INSTANCE = new SVC_A8_720();

	public String parse(int data) {
		throw new UnsupportedOperationException("SVC no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}
}