/*-------------------------------
 Auto Generated By AutoGenetate.java
     Don't remove or modify
        License GPL/GNU
-------------------------------*/
package com.marik.arm.OpCode.thumb.instruction16;

import com.marik.arm.OpCode.thumb.instruction16.support.ParseSupport;


@Deprecated
public class UDF_A8_758 extends ParseSupport {

	public static final UDF_A8_758 INSTANCE = new UDF_A8_758();

	public String parse(int data) {
		throw new UnsupportedOperationException("UDF no implements");
	}

	@Override
	public void performExecuteCommand(int data) {
	}
}